cache_path: ./model_src
data_path: 
  type1: ./data/type1
  type2: ./data/type2
  type3: ./data/type3
  type4: ./data/type4
embedding_model_name: AI-ModelScope/bge-small-zh-v1.5
embedding_model_path: ./
max_new_tokens: 2048
model_name: qwen/Qwen1.5-4B-Chat
model_path: ./model_int4
omp_num_threads: '20'
persist_dir: ./chroma_db
tokenizer_path: ./model_int4
