cache_path: ./model_src
data_path: 
  家庭关系: ./data/type1
  个人成长与心理: ./data/type2
  人际关系与社会适应: ./data/type3
  职业与学习: ./data/type4
embedding_model_name: AI-ModelScope/bge-small-zh-v1.5
embedding_model_path: ./model_src/AI-ModelScope/bge-small-zh-v1___5
max_new_tokens: 128
model_name: qwen/Qwen1.5-4B-Chat
model_path: ./model_int4
omp_num_threads: '8'
persist_dir: ./chroma_db
tokenizer_path: ./model_int4